server:
  port: 17688
spring:
  application:
    name: gateway-demo

  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        namespace: public
        group: DEFAULT_GROUP
        username: nacos
        password: 123456
        access-key: 123456
        secret-key: 123456

    gateway:
      routes:
        # 1. 基本路由
        - id: satoken-demo
          uri: lb://satoken-demo  # lb:// 表示负载均衡
          predicates:
            - Path=/satoken/**       # 路径匹配
          filters:
            - StripPrefix=1
  data:
    redis:
      host: localhost
      port: 6379
  datasource:
    username: micro
    password: 123456
    url: jdbc:mysql://localhost:3306/demo?useUnicode=true&characterEncoding=utf-8&autoReconnect=true&autoReconnectForPools=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource


mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-packag: com.chandler.*.domain

info:
  app:
    name: ${spring.application.name}
    description: @project.description@
    version: project.build.sourceEncoding@
    java:
      version: @java.version@


############## Sa-Token 配置 (文档: https://sa-token.cc) ##############
sa-token:
  # token 名称（同时也是 cookie 名称）
  token-name: satoken
  # token 有效期（单位：秒） 默认30天，-1 代表永久有效
  timeout: 2592000
  # token 最低活跃频率（单位：秒），如果 token 超过此时间没有访问系统就会被冻结，默认-1 代表不限制，永不冻结
  active-timeout: -1
  # 是否允许同一账号多地同时登录 （为 true 时允许一起登录, 为 false 时新登录挤掉旧登录）
  is-concurrent: true
  # 在多人登录同一账号时，是否共用一个 token （为 true 时所有登录共用一个 token, 为 false 时每次登录新建一个 token）
  is-share: false
  # token 风格（默认可取值：uuid、simple-uuid、random-32、random-64、random-128、tik）
  token-style: uuid
  # 是否输出操作日志
  is-log: true